name = "calendar-thing"
main = "src/index.ts"
compatibility_date = "2026-04-02"
preview_urls = true

[assets]
directory = "./public"

[[services]]
binding = "MOON_PHASE"
service = "moon-phase-calendar"

[[services]]
binding = "MOVIE_RELEASE"
service = "movie-release-calendar"
